### ISSUE TITLE
Document new middleware features

### ISSUE THREAD

**Issue by andersevenrud** [os-js/manual.os-js.org#33]
note-to-self: Update core article after this has been written to have the new provider

**Comment by andersevenrud** [comment]
@MoradiDavijani If you're up for writing documentation for this, then you can take this issue if you want :nerd_face:

**Comment by ThisIsOstad** [comment]
Sure, I'm going to work on it.

**Comment by andersevenrud** [comment]
Great!

**Comment by ThisIsOstad** [comment]
Could you give me an overview of the parts that should be added to the documentation?

**Comment by andersevenrud** [comment]
This can be placed under `Tutorials > Misc` section in `SUMMARY.md` and under `tutorial/middleware/README.md`. There is some special metadata that goes into the top of the file, but you can find examples of that in any other article in this repo.

What is needed is the following:

1. A brief description of use-cases
2. How to add middleware
3. How to use middleware
4. How to add middleware script to a package

**Comment by andersevenrud** [comment]
Aw. I forgot to link this issue to the PR.

Closing.

Thanks again :)
