### ISSUE TITLE
https://manual.os-js.org/v3/api has no index.html

### ISSUE THREAD

**Issue by RossComputerGuy** [os-js/manual.os-js.org#5]
https://manual.os-js.org/v3/api should have index.html which would list the api's that are available

**Comment by andersevenrud** [comment]
The overview can be found in the manual: https://manual.os-js.org/v3/resource/official/

**Comment by andersevenrud** [comment]
`/api` is just a reverse-proxy endpoint. So it's not actualy within the manual.

I can make a redirect there to the manual though.

**Comment by andersevenrud** [comment]
Added the redirect.
